buttun and inputs
A-S-T-R-A/Astra-Admin pull request #14
Opened 2023-04-26 15:44 UTC by SergeyTitov2019

2023-05-15 11:34 UTC, Art1us requested changes
Визуал:
1. У инпутов и текстэрии слишком большой паддинг слева, попробуй уменьшить
2. У текстэрии текст прилипает к верхней границе
3. Добавть дропдауну стрелочку вверх/вниз

Код:
1. Комментарии
2. Передавай названиям тестов семантические названия

2023-05-15 11:34 UTC, Art1us commented on src/shared/config/routeConfig/const.ts
> +    [AppRoutes.DEMO]: "demo",
/demo ??

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Button/Button.test.tsx
>      test("Button with filled-red class", () => {
Поправь названия тестов
тут уже не filled red

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Button/Button.tsx
> +import { ButtonHTMLAttributes, memo, ReactNode, useEffect } from "react"
зачем тут useEffect?

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    const [isChecked, setIsChecked] = useState(false)
в чекбоксе не должно быть внутреннего стейта.
Внешний компонент должен хранить стейт и только передавать пропсами checked и onChange

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    checked?: boolean
это обязательный пропс

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    positionCheckboxRight?: boolean
Тут лучше сделать variant, как в кнопках

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Dropdown/ui/Dropdown.tsx
> +    Foo?: (data: any) => void
что это за функция?

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Dropdown/ui/Dropdown.tsx
> +    const handleChange = (event: any) => {
any

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Input/Input.tsx
> +        console.log("e:", e)
консоль

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Textarea/Textarea.tsx
> +    value?: string | number
value текстэрии - всегда строка

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Textarea/Textarea.tsx
> +    rows?: number | undefined
знак вопроса подразумевает под собой undefined

2023-05-15 11:34 UTC, Art1us commented on src/shared/ui/Textarea/Textarea.tsx
> +        console.log("T e:", e)
консоль

2023-05-15 14:33 UTC, SergeyTitov2019 commented on src/shared/ui/Textarea/Textarea.tsx
> +        console.log("T e:", e)
done

2023-05-15 14:34 UTC, SergeyTitov2019 commented on src/shared/ui/Textarea/Textarea.tsx
> +    rows?: number | undefined
done

2023-05-15 14:35 UTC, SergeyTitov2019 commented on src/shared/ui/Textarea/Textarea.tsx
> +    value?: string | number
done

2023-05-15 14:35 UTC, SergeyTitov2019 commented on src/shared/ui/Input/Input.tsx
> +        console.log("e:", e)
done

2023-05-16 10:51 UTC, SergeyTitov2019 commented on src/shared/ui/Dropdown/ui/Dropdown.tsx
> +    const handleChange = (event: any) => {
done

2023-05-16 11:09 UTC, SergeyTitov2019 commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    checked?: boolean
done

2023-05-16 11:53 UTC, SergeyTitov2019 commented on src/shared/ui/Button/Button.tsx
> +import { ButtonHTMLAttributes, memo, ReactNode, useEffect } from "react"
done

2023-05-16 11:55 UTC, SergeyTitov2019 commented on src/shared/ui/Button/Button.test.tsx
>      test("Button with filled-red class", () => {
done

2023-05-16 11:57 UTC, SergeyTitov2019 commented on src/shared/config/routeConfig/const.ts
> +    [AppRoutes.DEMO]: "demo",
done

2023-05-17 13:48 UTC, SergeyTitov2019 commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    const [isChecked, setIsChecked] = useState(false)
done

2023-05-18 07:33 UTC, Art1us approved these changes

2023-05-18 07:33 UTC, merged