icons
A-S-T-R-A/Astra-Admin pull request #15
Opened 2023-05-25 12:22 UTC by SergeyTitov2019

2023-05-25 19:42 UTC, Art1us requested changes
комменты

2023-05-25 19:42 UTC, Art1us commented on src/shared/assets/icons/arrow-down.tsx
> +                    [styles.colorAccent]: color === "accent",
1. Будет сильно накладно таким образом добавлять классы, лучше всего добавить в массив в виде styles[color]
2. Также добавить className из пропса в массив
3. wrapper тут тоже не нужен, передай все в svg

2023-05-25 19:42 UTC, Art1us commented on src/shared/assets/icons/index.ts
> +import ArrowDown from "./arrow-down"
файлы старайся называть согласно компонентам

2023-05-26 11:16 UTC, SergeyTitov2019 commented on src/shared/assets/icons/index.ts
> +import ArrowDown from "./arrow-down"
done

2023-05-26 11:41 UTC, SergeyTitov2019 commented on src/shared/assets/icons/arrow-down.tsx
> +                    [styles.colorAccent]: color === "accent",
done

2023-05-26 20:18 UTC, Art1us approved these changes

2023-05-26 20:18 UTC, merged